function card = methodCard(methodName)
%METHODCARD What a method is, before it has been run.
%
%   Inputs
%     METHODNAME  which method
%
%   Outputs
%     CARD        where the method comes from, what it produces, and what its
%                 inner integral costs
%
%   Utility
%     Fill the Compare Methods tab's cards before anything has been run, which
%     is the one moment that tab exists for.
%
%   Static on purpose. A card that could only be filled in from a result would
%   be blank exactly when a user is deciding which methods to run, which is
%   the one moment the tab exists for. The dynamic half -- status, runtime,
%   whether the budgets actually matched -- is read off the results and shown
%   beside it.
%
%   PRODUCES is the field worth reading twice. Two of these three return an
%   unnormalized generated factor and one returns a density, and that
%   difference is why the comparison table has a mass-error column with a dash
%   in it rather than a number.

arguments
    methodName (1,1) string
end

switch methodName
    case "Slices"
        card = struct( ...
            'name',      "Slices", ...
            'origin',    "published", ...
            'notInPaper', false, ...
            'basedOn',   "Slices Perspective (Shienman et al., IROS 2024)", ...
            'spec',      "Slices spec, Algorithms S1-S3", ...
            'produces',  "an unnormalized generated factor f_new on a finite " + ...
                         "separator support, plus posterior samples from the " + ...
                         "backward pass. Its mass is a result in its own right.", ...
            'innerCost', "nested inner sampling, Eq. (23). Costs " + ...
                         "|X| x |L_n| factor evaluations per elimination, " + ...
                         "which is where its runtime goes.");

    case "Smoothed Slices"
        card = struct( ...
            'name',      "Smoothed Slices", ...
            'origin',    "proposed extension", ...
            'notInPaper', true, ...
            'basedOn',   "Slices Perspective (Shienman et al., IROS 2024)", ...
            'spec',      "Smoothed Slices spec, sections 10-11", ...
            'produces',  "the same unnormalized generated factor as Slices, " + ...
                         "through the same elimination. The two differ in one " + ...
                         "config field, so any other difference between them " + ...
                         "would be the harness rather than the method.", ...
            'innerCost', "cached conditional smoothing surface, Eq. (50). " + ...
                         "The nested sampling is removed rather than made " + ...
                         "cheaper; on a general graph the gain comes from the " + ...
                         "active successor sets instead.");

    case "NF-iSAM"
        card = struct( ...
            'name',      "NF-iSAM", ...
            'origin',    "published", ...
            'notInPaper', false, ...
            'basedOn',   "NF-iSAM: incremental smoothing with normalizing flows", ...
            'spec',      "NF-iSAM spec, Algorithms N1-N3", ...
            'produces',  "a NORMALIZED posterior: one flow per Bayes-tree " + ...
                         "clique, sampled root to leaf. There is no " + ...
                         "unnormalized f_new and therefore no mass error to " + ...
                         "report, and its curve on a grid is a kernel density " + ...
                         "estimate of the draws rather than something the " + ...
                         "method produced.", ...
            'innerCost', "none. Algorithm N1 is generative: it draws from a " + ...
                         "factor and never asks one for a value, so its factor " + ...
                         "evaluation count is genuinely 0. What it spends " + ...
                         "instead is one flow fit per clique.");

    otherwise
        error('methods:methodCard:unknownMethod', ...
            'No card for method "%s".', methodName);
end

card.figures = methods.figureRegistryFor(methodName).names;
end
