function rec = implementationRecord(methodName, engine)
%IMPLEMENTATIONRECORD What a method's implementation does and does not claim.
%
%   Inputs
%     methodName   "Slices" | "Smoothed Slices" | "NF-iSAM"
%     engine       "three_node_demo" | "general_importance_sampling" |
%                  "bayes_tree_flow"
%
%   Outputs
%     rec          struct with fields
%       methodFamily        "slices" | "smoothed_slices" | "nfisam"
%       paperReference      the paper object this route implements
%       paperFidelity       "paper_demo" | "implementation_generalization" |
%                           "prototype_extension"
%       engine              as given
%       mainDeviation       the one departure that matters most
%       deviationList       every known departure, most significant first
%       scopeWarning        what a reader must not conclude from a result
%       canClaimPaperExact  true only for a route validated against a
%                           reference and matching the paper's own object
%
%   Utility
%     Gives every result a machine-readable statement of its own fidelity, so
%     the app, the exported diagnostics and the report can say what a number is
%     without anyone having to remember. Attached by runInferenceCore,
%     runGeneralCore and runNFISAMMethod.
%
%   ONE FUNCTION RATHER THAN THREE COPIES. The three drivers would otherwise
%   each carry their own wording and drift apart, and the claim that must not
%   be made is exactly the kind that survives in the copy nobody edited.
%
%   FIDELITY DEPENDS ON THE ENGINE, NOT ONLY THE METHOD, which is the whole
%   reason this exists. Slices on the three-node route follows Algorithm S1
%   literally and is checked against dense quadrature, so it can claim the
%   paper. The SAME method on the general graph engine is importance sampling
%   with explicit proposal densities and a finite support lookup -- a
%   generalization the paper does not describe -- and claiming the paper for
%   both because the method name is the same is the specific error this guards.
%
%   See also methods.methodCard, methods.runInferenceCore, methods.runGeneralCore.

arguments
    methodName (1,1) string
    engine (1,1) string {mustBeMember(engine, ["three_node_demo", ...
        "general_importance_sampling", "bayes_tree_flow"])}
end

switch methodName
    case "Slices"
        rec = localSlices(engine);
    case "Smoothed Slices"
        rec = localSmoothed(engine);
    case "NF-iSAM"
        rec = localNfisam(engine);
    otherwise
        error('methods:implementationRecord:unknownMethod', ...
            'No implementation record for method "%s".', methodName);
end

rec.engine = engine;
end

% =========================================================================
function rec = localSlices(engine)
%LOCALSLICES Slices, whose fidelity is the one that genuinely differs by engine.
%   Inputs   engine
%   Outputs  rec  without the engine field, which the caller sets
%   Utility  Separates the paper-literal demonstrator from the generalization,
%            because only the first can claim Algorithm S1.
common = struct( ...
    'methodFamily',  "slices", ...
    'paperReference', "Slices Perspective (Shienman et al., IROS 2024), " + ...
                      "Eq. (11)-(16), Algorithms S1-S3");

if engine == "three_node_demo"
    rec = common;
    rec.paperFidelity = "paper_demo";
    rec.mainDeviation = "none known on this route";
    rec.deviationList = "the separator restriction in the Lemma 1 path is " + ...
        "scalar, so this route does not demonstrate a high-dimensional separator";
    rec.scopeWarning = "Paper-faithful for the controlled Eq. (16) " + ...
        "demonstrator only. Says nothing about the general graph engine, " + ...
        "which is a different implementation under the same method name.";
    rec.canClaimPaperExact = true;
    return
end

rec = common;
rec.paperFidelity = "implementation_generalization";
rec.mainDeviation = "the general graph engine is importance sampling with " + ...
    "explicit proposal densities and a finite support lookup, which the " + ...
    "paper does not describe";
rec.deviationList = [ ...
    "generated factors are tabulated on a finite separator support and " + ...
    "looked up, rather than used as slices in place"; ...
    "proposal densities are formed per variable and mixed, so the weights " + ...
    "are importance weights rather than the paper's slice evaluation"; ...
    "measured weight degeneracy on real data: minimum essSupport of 1.0 to " + ...
    "2.4 out of 201 on the Plaza1 lap window"];
rec.scopeWarning = "An implementation generalization, NOT Algorithm S1. " + ...
    "Results on this engine must not be presented as reproducing the paper.";
rec.canClaimPaperExact = false;
end

% =========================================================================
function rec = localSmoothed(engine)
%LOCALSMOOTHED Smoothed Slices, which is not in any paper on either engine.
%   Inputs   engine
%   Outputs  rec  without the engine field
%   Utility  A proposed extension, so paperFidelity is prototype_extension
%            whichever engine ran it; only the deviations differ.
rec = struct( ...
    'methodFamily',  "smoothed_slices", ...
    'paperReference', "proposed extension built on the Slices Perspective " + ...
                      "factorization; Smoothed Slices spec sections 10-11", ...
    'paperFidelity', "prototype_extension");

if engine == "three_node_demo"
    rec.mainDeviation = "finite-support Mode A with a one-level " + ...
        "conditional smoothing surface, not the full recursive R_r tower";
    rec.deviationList = [ ...
        "one level of conditional smoothing replaces the nested estimate; " + ...
        "the recursive surface tower of the spec is not implemented"; ...
        "surfaceMode ""basis"" and ""regression"" are accepted by the config " + ...
        "validator and then refused at run time; only ""finite"" exists"];
else
    % The strongest statement in this file, and it is the accurate one. On a
    % general graph NO conditional smoothing surface is built at all: the only
    % thing separating this method from Slices is that the slice matrix has
    % its smallest separator entries zeroed. Calling that an active-set sparse
    % R_r evaluation, as this record previously did, credits the method with
    % the mechanism it is named for.
    rec.mainDeviation = "on a general graph NO recursive surface is built: " + ...
        "the only difference from Slices is that each slice row's smallest " + ...
        "separator entries are zeroed";
    rec.deviationList = [ ...
        "the recursive R_r tower of spec sections 9-11 is not implemented on " + ...
        "this engine; runSmoothedSlicesMethod sets activeSetSize to a " + ...
        "fraction of |S|, and the general engine prunes SEPARATOR support " + ...
        "points, not the successor path points N_r(a) of Eq. (49)"; ...
        "the pruned rows are NOT renormalized, so f_new(s) is exactly zero " + ...
        "at any separator point no outer sample ranked in its top K: the " + ...
        "support of the answer is truncated, not merely coarsened"; ...
        "the error this causes on a general graph is UNMEASURED; the K sweep " + ...
        "that produced the retained-mass threshold was run on the two-pose " + ...
        "route, where the pruning is over successors and is renormalized"; ...
        "measured weight degeneracy on real data: minimum essSupport of 1.0 " + ...
        "to 2.4 out of 201 on the Plaza1 lap window"];
end

rec.scopeWarning = "A PROPOSED EXTENSION. Not part of the Slices paper, " + ...
    "and not to be described as reproducing it. The conditional smoothing " + ...
    "surface reorganizes and approximates the inner integral; it does not " + ...
    "remove it.";
rec.canClaimPaperExact = false;
end

% =========================================================================
function rec = localNfisam(engine)
%LOCALNFISAM NF-iSAM, which follows the paper's shape with a rebuilt tree.
%   Inputs   engine
%   Outputs  rec  without the engine field
%   Utility  Records the four departures that make this a generalization
%            rather than a reproduction, including the training cap.
if engine ~= "bayes_tree_flow"
    error('methods:implementationRecord:wrongEngine', ...
        'NF-iSAM runs on the bayes_tree_flow engine, not "%s".', engine);
end

rec = struct( ...
    'methodFamily',  "nfisam", ...
    'paperReference', "NF-iSAM (Huang et al., T-RO 2023), Bayes-tree clique " + ...
                      "conditionals p(F_C | S_C, z_C), Algorithms N1-N3", ...
    'paperFidelity', "implementation_generalization", ...
    'mainDeviation', "the Bayes tree is rebuilt each increment and reused by " + ...
                     "clique identity, rather than updated in place", ...
    'deviationList', [ ...
        "the tree is rebuilt per increment; reuse is keyed on clique " + ...
        "identity, not on which factors changed"; ...
        "child separator information is propagated through samples and " + ...
        "resampling, which is approximate where the overlap is partial"; ...
        "the conditional samplers are a custom MATLAB RQ-spline flow, not " + ...
        "the reference implementation"; ...
        "flow training carries a MaxIterations cap chosen for interactive " + ...
        "use; a fit that stops there stopped on budget, not on convergence"], ...
    'scopeWarning', "Follows the paper's factorization with a rebuilt tree " + ...
        "and a custom flow. Produces NORMALIZED posterior samples: there is " + ...
        "no unnormalized f_new, so mass error does not apply, and any grid " + ...
        "curve is a kernel density estimate of the draws. Its zero factor " + ...
        "evaluation count means cost moved to flow training, not that it is " + ...
        "free.", ...
    'canClaimPaperExact', false);
end
